In [20]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
import matplotlib.pyplot as plt
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("WeatherPy_database.csv")
city_data_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hours),Snow inches (last 3 hours)
0,0,Saskylakh,RU,2020-07-12 21:11:58,71.92,114.08,59.54,72,89,16.42,overcast clouds,0,0
1,1,Rikitea,PF,2020-07-12 21:12:14,-23.12,-134.97,71.04,71,0,16.71,clear sky,0,0
2,2,Chaman,PK,2020-07-12 21:15:37,30.92,66.45,75.09,25,0,5.64,clear sky,0,0
3,3,Ushuaia,AR,2020-07-12 21:12:45,-54.80,-68.30,35.60,94,40,18.34,scattered clouds,0,0
4,4,Narsaq,GL,2020-07-12 21:12:41,60.92,-46.05,57.20,50,100,6.93,overcast clouds,0,0
5,5,Ostrovnoy,RU,2020-07-12 21:15:38,68.05,39.51,48.11,91,100,7.07,overcast clouds,0,0
6,6,Moroni,KM,2020-07-12 21:15:38,-11.70,43.26,76.24,72,4,3.38,clear sky,0,0
7,7,Miri,MY,2020-07-12 21:15:38,4.41,114.01,78.01,100,40,3.47,scattered clouds,0,0
8,8,Margate,GB,2020-07-12 21:15:38,51.38,1.39,60.01,69,86,1.01,overcast clouds,0,0
9,9,Beian,NO,2020-07-12 21:15:39,63.66,9.57,51.80,81,75,14.99,shower rain,0,0

In [3]:
# Ask the customer to add a minimum, maximum temperature value, and if he'she likes to have rain/snow:
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
rain_input = str(input("Do you want it to be raining? (yes/no) "))
snow_input = str(input("Do you want it to be snowing? (yes/no) "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90
Do you want it to be raining? (yes/no) no
Do you want it to be snowing? (yes/no) no

In [4]:
# Convert customer input:
if rain_input.lower() == "yes":
    with_rain = city_data_df['Rain inches (last 3 hours)'] > 0
else:
    with_rain = city_data_df['Rain inches (last 3 hours)'] == 0
    
if snow_input.lower() == "yes":
    with_snow = city_data_df['Snow inches (last 3 hours)'] > 0
else:
    with_snow = city_data_df['Snow inches (last 3 hours)'] == 0
    
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) & \
                                       with_rain & with_snow
                                      ]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hours),Snow inches (last 3 hours)
2,2,Chaman,PK,2020-07-12 21:15:37,30.92,66.45,75.09,25,0,5.64,clear sky,0,0
6,6,Moroni,KM,2020-07-12 21:15:38,-11.70,43.26,76.24,72,4,3.38,clear sky,0,0
7,7,Miri,MY,2020-07-12 21:15:38,4.41,114.01,78.01,100,40,3.47,scattered clouds,0,0
10,10,Tirumullaivasal,IN,2020-07-12 21:15:39,11.23,79.83,83.34,70,90,11.63,light rain,0,0
14,14,Tezu,IN,2020-07-12 21:15:21,27.92,96.17,75.06,86,100,2.91,moderate rain,0,0
16,16,Kenora,CA,2020-07-12 21:15:41,49.82,-94.43,75.20,50,75,4.70,shower rain,0,0
18,18,Atuona,PF,2020-07-12 21:15:41,-9.80,-139.03,80.60,73,1,22.46,clear sky,0,0
19,19,Alofi,NU,2020-07-12 21:15:42,-19.06,-169.92,75.20,83,100,21.92,overcast clouds,0,0
23,23,Sao Joao Da Barra,BR,2020-07-12 21:15:43,-21.64,-41.05,75.20,73,89,8.05,overcast clouds,0,0
25,25,Jamestown,US,2020-07-12 21:11:10,42.10,-79.24,75.00,60,1,12.75,clear sky,0,0

In [5]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Chaman,PK,75.09,clear sky,30.92,66.45,
6,Moroni,KM,76.24,clear sky,-11.70,43.26,
7,Miri,MY,78.01,scattered clouds,4.41,114.01,
10,Tirumullaivasal,IN,83.34,light rain,11.23,79.83,
14,Tezu,IN,75.06,moderate rain,27.92,96.17,
...,...,...,...,...,...,...,...
552,Lardos,GR,78.80,clear sky,36.09,28.02,
553,Pimenta Bueno,BR,88.57,clear sky,-11.67,-61.19,
554,Benito Juarez,MX,78.80,scattered clouds,19.39,-99.17,
556,Amahai,ID,76.71,moderate rain,-3.33,128.92,
562,Hudson Bay,CA,79.34,overcast clouds,52.85,-102.38,

In [6]:

# Retrieve hotels from nearby search on Google:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [8]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
        
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

hotel_df

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Chaman,PK,75.09,clear sky,30.92,66.45,Niamatt parda Center
6,Moroni,KM,76.24,clear sky,-11.70,43.26,Hotel les Arcades
7,Miri,MY,78.01,scattered clouds,4.41,114.01,"Mega Hotel, Miri"
10,Tirumullaivasal,IN,83.34,light rain,11.23,79.83,"MATHAMPATTINAM, MODUNUTTI GROUP"
14,Tezu,IN,75.06,moderate rain,27.92,96.17,Circuit House
...,...,...,...,...,...,...,...
552,Lardos,GR,78.80,clear sky,36.09,28.02,Lindos Princess Beach Hotel
553,Pimenta Bueno,BR,88.57,clear sky,-11.67,-61.19,Cristalina Palace Hotel
554,Benito Juarez,MX,78.80,scattered clouds,19.39,-99.17,Room Mate Valentina Hotel
556,Amahai,ID,76.71,moderate rain,-3.33,128.92,Hotel isabella
562,Hudson Bay,CA,79.34,overcast clouds,52.85,-102.38,Norwood Motel LTD

In [9]:
# Remove blank hotel
hotel_df = hotel_df.loc[hotel_df['Hotel Name'] != ""]
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Chaman,PK,75.09,clear sky,30.92,66.45,Niamatt parda Center
6,Moroni,KM,76.24,clear sky,-11.70,43.26,Hotel les Arcades
7,Miri,MY,78.01,scattered clouds,4.41,114.01,"Mega Hotel, Miri"
10,Tirumullaivasal,IN,83.34,light rain,11.23,79.83,"MATHAMPATTINAM, MODUNUTTI GROUP"
14,Tezu,IN,75.06,moderate rain,27.92,96.17,Circuit House
...,...,...,...,...,...,...,...
552,Lardos,GR,78.80,clear sky,36.09,28.02,Lindos Princess Beach Hotel
553,Pimenta Bueno,BR,88.57,clear sky,-11.67,-61.19,Cristalina Palace Hotel
554,Benito Juarez,MX,78.80,scattered clouds,19.39,-99.17,Room Mate Valentina Hotel
556,Amahai,ID,76.71,moderate rain,-3.33,128.92,Hotel isabella
562,Hudson Bay,CA,79.34,overcast clouds,52.85,-102.38,Norwood Motel LTD

In [10]:
# Create the output file (CSV).
output_data_file = "WeatherPy_vacation.csv"
# Export the hotel_df into a CSV.
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# Create pop-up markers:
# HTML code:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

In [12]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [13]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [23]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# heat layer for temp is not required:
    # heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False, max_intensity=300, point_radius=4)
    # fig.add_layer(heat_layer)

# add pop-up marker:
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Save the figure.
plt.savefig("WeatherPy_vacation_map.png")

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))